/**
 * Batch import all watches into Sanity CMS.
 *
 * Usage:
 *   1. Go to https://sanity.io/manage → project ihki5wi0 → API → Tokens
 *   2. Create a token with Editor permissions
 *   3. SANITY_TOKEN=your_token node scripts/import-watches.mjs
 *
 * Already in Sanity (will be skipped):
 *   - 1815 Rattrapante Perpetual Calendar
 *   - 1815 Flyback Chronograph
 *   - Zeitwerk (rose gold)
 *   - 222 (VC steel)
 *   - Daytona Rainbow
 */

import { createClient } from '@sanity/client'
import crypto from 'crypto'

const token = process.env.SANITY_TOKEN
if (!token) {
  console.error('Missing SANITY_TOKEN. See instructions at top of file.')
  process.exit(1)
}

const client = createClient({
  projectId: 'ihki5wi0',
  dataset: 'production',
  apiVersion: '2024-01-01',
  token,
  useCdn: false,
})

function slug(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

function key() {
  return crypto.randomBytes(6).toString('hex')
}

function text(content) {
  return [{ _type: 'block', _key: key(), style: 'normal', markDefs: [], children: [{ _type: 'span', _key: key(), text: content, marks: [] }] }]
}

// All watches — skip the 5 already in Sanity
const watches = [

  // ── A. Lange & Söhne ─────────────────────────────────────────────────────

  {
    name: 'Datograph Perpetual Tourbillon 092/100',
    maker: 'A. Lange & Söhne',
    reference: '740.039',
    year: '2015',
    caseMaterial: 'Honey gold',
    caseDiameter: '41mm',
    movement: 'Calibre L952.1 — manually wound, flyback chronograph, perpetual calendar, tourbillon',
    complications: 'Flyback chronograph, perpetual calendar, tourbillon',
    filterCategory: 'lange',
    order: 6,
    description: text(`One of three from the 092/100 matched set — the rarest grouping in Lange history. Honey gold case, handguilloché silver dial. The most complicated Lange ever made at the time of its creation.`),
    notes: text(`092/100 matched set acquired together. The Datograph Perpetual Tourbillon is piece one of the three. Matching serial numbers mark these as a planned unit.`),
  },
  {
    name: 'Lange 1 Ewiger Kalender 092/100',
    maker: 'A. Lange & Söhne',
    reference: '130.032',
    year: '2015',
    caseMaterial: 'Honey gold',
    caseDiameter: '41.9mm',
    movement: 'Calibre L021.3 — manually wound, perpetual calendar',
    complications: 'Perpetual calendar, moon phase',
    filterCategory: 'lange',
    order: 7,
    description: text(`One of three from the 092/100 matched set. TC's favourite of the trio — the perpetual calendar mechanism integrated into the asymmetric Lange 1 layout achieves a visual logic that feels inevitable in retrospect.`),
    notes: text(`092/100 matched set. The Lange 1 Ewiger Kalender represents the purest expression of the Lange 1 concept — taken to its logical perpetual extreme.`),
  },
  {
    name: 'Datograph Flyback',
    maker: 'A. Lange & Söhne',
    reference: '171.036',
    year: '2012',
    caseMaterial: 'White gold',
    caseDiameter: '41mm',
    movement: 'Calibre L951.6 — manually wound, flyback chronograph',
    complications: 'Flyback chronograph',
    filterCategory: 'lange',
    order: 8,
    description: text(`Blue dial on white gold — the Datograph Flyback in its most restrained configuration. The flyback mechanism allows the chronograph to be reset and restarted in a single gesture.`),
    notes: text(`White gold case with blue dial. Acquired for the cool-toned contrast it offers within a predominantly warm-metal collection.`),
  },
  {
    name: 'Richard Lange Tourbillon Pour le Mérite No. 38',
    maker: 'A. Lange & Söhne',
    reference: '760.052',
    year: '2018',
    caseMaterial: 'Platinum',
    caseDiameter: '41.9mm',
    movement: 'Calibre L044.2 — chain-and-fusee, tourbillon',
    complications: 'Tourbillon, chain-and-fusee transmission',
    filterCategory: 'lange',
    order: 9,
    description: text(`Piece No. 38 — acquired on March 8, TC's birthday. The diamond bezel version of the Pour le Mérite, making it among the rarest Lange references extant. The chain-and-fusee transmission, revived from 18th-century pocket watchmaking, delivers constant torque to the balance wheel.`),
    notes: text(`Acquired on March 8 — TC's birthday. Diamond bezel. The Pour le Mérite name refers to a Prussian order of merit, connecting Lange's Glashütte identity to its historical context.`),
  },
  {
    name: 'Lange 1 Doppelfederhaus',
    maker: 'A. Lange & Söhne',
    reference: '191.025',
    year: '2011',
    caseMaterial: 'Platinum',
    caseDiameter: '41.9mm',
    movement: 'Calibre L121.2 — twin mainspring barrel, 10-day power reserve',
    complications: '10-day power reserve',
    filterCategory: 'lange',
    order: 10,
    description: text(`Platinum case with green strap. The Doppelfederhaus — twin mainspring barrel — stores enough energy for ten days of continuous running. One of the most architecturally honest Lange 1 variants: every complication visible serves an observable function.`),
    notes: text(`Platinum case on green strap. The Doppelfederhaus represents Lange at its most technically assured — no complications for spectacle, only those that extend function.`),
  },
  {
    name: 'Lange 1 Timezone',
    maker: 'A. Lange & Söhne',
    reference: '116.032',
    year: '2013',
    caseMaterial: 'Rose gold',
    caseDiameter: '41.9mm',
    movement: 'Calibre L031.1 — world time with day/night indication',
    complications: 'World time, day/night indication',
    filterCategory: 'lange',
    order: 11,
    description: text(`Rose gold with black dial and blue strap. The Timezone translates the Lange 1 asymmetry into a travel complication — a world time display with 24 city references, the day/night arc illuminated by a blued hand.`),
    notes: text(`Rose gold, black dial, blue strap. Acquired for the travel utility and the elegance of how Lange solved a functional problem without abandoning the canonical Lange 1 layout.`),
  },
  {
    name: 'Zeitwerk Minute Repeater',
    maker: 'A. Lange & Söhne',
    reference: '145.032',
    year: '2016',
    caseMaterial: 'Rose gold',
    caseDiameter: '44.2mm',
    movement: 'Calibre L043.5 — jumping numerals, minute repeater',
    complications: 'Jumping numeral display, minute repeater',
    filterCategory: 'lange',
    order: 12,
    description: text(`The second Zeitwerk in the collection — rose gold with black dial. The Zeitwerk family represents a radical rethinking of time display: digital numerals on an analog movement. The Minute Repeater variant adds an acoustic dimension to the mechanical spectacle.`),
    notes: text(`Rose gold, black dial. Part of a pair of Zeitwerk references. The jumping disc mechanism requires a constant-force escapement to maintain display accuracy despite the energy spikes.`),
  },
  {
    name: '1815 Auf/Ab',
    maker: 'A. Lange & Söhne',
    reference: '234.050',
    year: '2014',
    caseMaterial: 'Rose gold',
    caseDiameter: '40mm',
    movement: 'Calibre L051.3 — manually wound, power reserve indicator',
    complications: 'Power reserve indication',
    filterCategory: 'lange',
    order: 13,
    description: text(`The 1815 Auf/Ab — Auf for wound, Ab for run down — in rose gold. Among the most disciplined of Lange's references: a manually wound movement with nothing to show beyond the time and the state of its own energy. The dial's railway-track minute ring and Breguet numerals reference 19th-century pocket watch typography.`),
    notes: text(`Rose gold. The 1815 family is named for the year Adolph Lange established watchmaking standards in Saxony. This piece represents the line at its most composed.`),
  },
  {
    name: 'Richard Lange Pour le Mérite',
    maker: 'A. Lange & Söhne',
    reference: '261.025',
    year: '2010',
    caseMaterial: 'Platinum',
    caseDiameter: '40.5mm',
    movement: 'Calibre L041.2 — chain-and-fusee, three-wheel train',
    complications: 'Chain-and-fusee transmission',
    filterCategory: 'lange',
    order: 14,
    description: text(`The original Richard Lange Pour le Mérite — platinum case, chain-and-fusee transmission. A time-only watch of supreme mechanical conviction. The visible chain wrapping the fusee cone is among the most arresting sights in watchmaking.`),
    notes: text(`Platinum. The Pour le Mérite predates the Tourbillon variant. Acquired first — the Tourbillon No. 38 followed years later.`),
  },
  {
    name: 'Saxonia Thin',
    maker: 'A. Lange & Söhne',
    reference: '211.066',
    year: '2016',
    caseMaterial: 'White gold',
    caseDiameter: '40mm',
    movement: 'Calibre L093.1 — manually wound, 72-hour power reserve, 2.9mm thick',
    complications: 'Ultra-thin',
    filterCategory: 'lange',
    order: 15,
    description: text(`White gold with black dial and grey strap. The Saxonia Thin is Lange at its most minimal — a 2.9mm movement inside a case barely thicker than a fingernail. Nothing is hidden, nothing is decorative: the movement IS the watch.`),
    notes: text(`White gold, black dial, grey strap. The Saxonia Thin is the reference TC reaches for when the occasion demands invisibility. An argument that restraint is its own form of statement.`),
  },
  {
    name: 'Odysseus',
    maker: 'A. Lange & Söhne',
    reference: '363.169',
    year: '2019',
    caseMaterial: 'Stainless steel',
    caseDiameter: '40.5mm',
    movement: 'Calibre L155.1 — automatic, annual calendar',
    complications: 'Annual calendar, date, day of week',
    filterCategory: 'lange',
    order: 16,
    description: text(`Lange's first sports watch — and its first stainless steel watch in the modern era. The Odysseus represented a deliberate expansion of what Lange considered acceptable material. The integrated bracelet and rotating bezel are antithetical to everything the maison had stood for. That tension makes it interesting.`),
    notes: text(`Stainless steel. The Odysseus is the collection's only sports watch. Acquired to understand what Lange becomes under constraint — the same intellectual rigour applied to a different brief.`),
  },
  {
    name: 'Vintage Lange — 1930s Pre-War',
    maker: 'A. Lange & Söhne',
    reference: '',
    year: '1930s',
    caseMaterial: 'Yellow gold',
    caseDiameter: '36mm',
    movement: 'Pre-war manually wound',
    complications: '',
    filterCategory: 'lange',
    order: 17,
    description: text(`The first vintage Lange — discovered Hong Kong, March 2026. Pre-war Dresden production, before the division of Germany displaced Glashütte watchmaking east. The dial typography and case proportions belong to a different era of German precision.`),
    notes: text(`Found Hong Kong March 2026. This piece connects the modern Lange revival directly to its pre-war origins in Dresden. A reminder that the brand is older than its 1990 re-establishment.`),
  },

  // ── Patek Philippe ────────────────────────────────────────────────────────

  {
    name: 'Reference 5370P Split-Seconds Chronograph',
    maker: 'Patek Philippe',
    reference: '5370P-001',
    year: '2015',
    caseMaterial: 'Platinum',
    caseDiameter: '41mm',
    movement: 'Calibre CHR 29-535 PS — manually wound, split-seconds chronograph',
    complications: 'Split-seconds chronograph',
    filterCategory: 'patek',
    order: 18,
    description: text(`Platinum case, slate grey dial. The 5370P was the first Patek split-seconds chronograph with the new in-house CHR 29-535 PS movement — a milestone after decades of using ébauches. The rattrapante mechanism allows simultaneous timing of two concurrent events.`),
    notes: text(`Platinum. The 5370P announced a new era of Patek chronograph independence. Its grey dial and classical layout place it in direct conversation with vintage complicated Pateks.`),
  },
  {
    name: 'Grand Complication',
    maker: 'Patek Philippe',
    reference: '5002J',
    year: '2000s',
    caseMaterial: 'Rose gold',
    caseDiameter: '38mm',
    movement: 'Calibre R 27 QR SID LU CL — perpetual calendar, tourbillon, minute repeater, split-seconds chronograph',
    complications: 'Perpetual calendar, tourbillon, minute repeater, split-seconds chronograph',
    filterCategory: 'patek',
    order: 19,
    description: text(`Engraved rose gold Sky Moon Tourbillon — among the most complex watches Patek Philippe produces. The case back displays a celestial chart of the night sky above Geneva. The engravings on the case are done entirely by hand.`),
    notes: text(`Rose gold, hand-engraved case and movement. The Sky Moon Tourbillon is the summit of Patek complication architecture. Acquiring one requires a relationship with the maison.`),
  },
  {
    name: 'Perpetual Calendar Chronograph',
    maker: 'Patek Philippe',
    reference: '5970R',
    year: '2006',
    caseMaterial: 'Rose gold',
    caseDiameter: '40mm',
    movement: 'Calibre CH 27-70 Q — manually wound, perpetual calendar, split-seconds chronograph',
    complications: 'Perpetual calendar, split-seconds chronograph',
    filterCategory: 'patek',
    order: 20,
    description: text(`Rose gold on bracelet. The 5970 was the final evolution of the perpetual calendar chronograph line before the 5270 replaced it. Its combination of complications in a classical case represents a high watermark of Patek Geneva complication philosophy.`),
    notes: text(`Rose gold on bracelet. The 5970R is among the most coveted Patek references — a perpetual calendar and split-seconds chronograph in one case. Acquired on bracelet, which is the less common configuration.`),
  },
  {
    name: 'Golden Ellipse',
    maker: 'Patek Philippe',
    reference: '5738G',
    year: '2015',
    caseMaterial: 'White gold',
    caseDiameter: '38.5mm × 32mm',
    movement: 'Calibre 240 — ultra-thin automatic',
    complications: 'Ultra-thin',
    filterCategory: 'patek',
    order: 21,
    description: text(`White gold with blue dial. The Golden Ellipse's dimensions are derived from the golden ratio — the horizontal and vertical axes are in proportion 1:1.6180. Among Patek's most self-consciously beautiful references.`),
    notes: text(`White gold, blue dial. The Golden Ellipse is TC's sartorial Patek — worn when the occasion calls for ornament over declaration.`),
  },
  {
    name: 'Reference 1527',
    maker: 'Patek Philippe',
    reference: '1527',
    year: '1943',
    caseMaterial: 'Yellow gold',
    caseDiameter: '33mm',
    movement: 'Calibre 13-130 — manually wound, perpetual calendar, split-seconds chronograph',
    complications: 'Perpetual calendar, split-seconds chronograph',
    filterCategory: 'patek',
    order: 22,
    description: text(`A 1943 perpetual calendar chronograph in yellow gold — one of perhaps a dozen survivors. The Reference 1527 predates Patek's post-war complication orthodoxy. Its sector dial layout and vintage lug geometry belong to a period when Patek made watches for individual customers, not categories.`),
    notes: text(`Acquired Hong Kong March 2026 through Johnson167. Two-tone dial, yellow gold case. Price range $30,000–$45,000 USD. The 1527 is among the rarest vintage Patek references — and one of the most significant acquisitions in the collection.`),
  },

  // ── Vacheron Constantin ───────────────────────────────────────────────────

  {
    name: 'Tourbillon Perpetual Calendar',
    maker: 'Vacheron Constantin',
    reference: '43031',
    year: '2010',
    caseMaterial: 'Platinum',
    caseDiameter: '42mm',
    movement: 'Calibre 2795 — manually wound, perpetual calendar, tourbillon',
    complications: 'Perpetual calendar, tourbillon',
    filterCategory: 'vc',
    order: 23,
    description: text(`Platinum case on blue strap — the Vacheron Tourbillon Perpetual Calendar in its most austere configuration. The tourbillon cage rotates once per minute through an aperture at 6 o'clock, while the perpetual calendar disc arrangement occupies the upper register with Genevan economy.`),
    notes: text(`Platinum on blue strap. Vacheron Constantin Manufacture visit planned. This piece will be brought for the manufacture conversation.`),
  },
  {
    name: 'Overseas Perpetual Calendar Ultra-Thin',
    maker: 'Vacheron Constantin',
    reference: '4300V/120R-B067',
    year: '2016',
    caseMaterial: 'Rose gold',
    caseDiameter: '41.5mm',
    movement: 'Calibre 1120 QP — ultra-thin automatic, perpetual calendar',
    complications: 'Perpetual calendar, moon phase',
    filterCategory: 'vc',
    order: 24,
    description: text(`Rose gold Overseas Perpetual Calendar — a perpetual calendar in a sports case, rendered at 8.1mm total thickness. The Overseas interchangeable strap system allows the watch to transition between rubber sport and alligator dress configurations in seconds.`),
    notes: text(`Rose gold. The Overseas Perpetual Calendar is the collection\'s concession to wearability in a complication watch — a perpetual calendar that can be worn at the beach.`),
  },
  {
    name: '222 Rose Gold',
    maker: 'Vacheron Constantin',
    reference: '44018',
    year: '1977',
    caseMaterial: 'Rose gold',
    caseDiameter: '37mm',
    movement: 'Calibre 2121 — ultra-thin automatic',
    complications: 'Ultra-thin integrated bracelet',
    filterCategory: 'vc',
    order: 25,
    description: text(`A second 222 — this one in rose gold with cream dial. The 222 preceded the Overseas and established the integrated bracelet aesthetic for Vacheron. Designed by Jörg Hysek in 1977 for the brand\'s 222nd anniversary, it has never been as famous as its Royal Oak contemporary. That obscurity is part of its appeal.`),
    notes: text(`Rose gold with cream dial. The second of two 222 references in the collection. Together they span the production range — steel and rose gold, blue and cream dial.`),
  },
  {
    name: 'Skeletonised Perpetual Calendar',
    maker: 'Vacheron Constantin',
    reference: '43175',
    year: '2012',
    caseMaterial: 'White gold',
    caseDiameter: '44mm',
    movement: 'Calibre 1120 QP/1 — skeletonised, perpetual calendar',
    complications: 'Perpetual calendar, skeletonisation',
    filterCategory: 'vc',
    order: 26,
    description: text(`White gold skeletonised perpetual calendar on blue strap — the movement architecture exposed and partially removed to create a lace-like visual field. The perpetual calendar mechanism is legible not just as information but as mechanism.`),
    notes: text(`White gold on blue strap. The skeletonisation is done by hand — each bridge individually shaped and bevelled. One of the more technically demanding finishing operations in high watchmaking.`),
  },
  {
    name: 'Reference 4072 Chronograph',
    maker: 'Vacheron Constantin',
    reference: '4072',
    year: '1953',
    caseMaterial: '18k pink gold',
    caseDiameter: '36mm',
    movement: 'Calibre 492 — manually wound, single-pushpiece chronograph',
    complications: 'Chronograph',
    filterCategory: 'vc',
    order: 27,
    description: text(`A 1953 single-pushpiece chronograph in 18k pink gold — movement serial number 33166995, calibre 492. Among the most significant vintage pieces in the collection. Being brought to the Vacheron Constantin manufacture visit in Geneva for authentication and service discussion.`),
    notes: text(`Movement #33166995, Calibre 492, 1953. Pink gold case. Being brought to the VC manufacture visit — this piece connects the planned relationship with the maison to its actual history.`),
  },

  // ── Grand Seiko ───────────────────────────────────────────────────────────

  {
    name: 'Spring Drive 5 Days Birch (Blue)',
    maker: 'Grand Seiko',
    reference: 'SBDB031',
    year: '2019',
    caseMaterial: 'Titanium',
    caseDiameter: '43.5mm',
    movement: 'Calibre 9R65 — Spring Drive, 5-day power reserve',
    complications: 'Spring Drive, 5-day power reserve',
    filterCategory: 'gs',
    order: 28,
    description: text(`Blue birch dial on titanium bracelet — the surface of the dial etched to reproduce the bark texture of birch trees in the Shinshu forest adjacent to the Shinshu Watch Studio where it was made. The Spring Drive mechanism is neither quartz nor mechanical but a third category: a mechanical movement regulated by electromagnetic braking.`),
    notes: text(`Blue dial, titanium bracelet. Shinshu Studio production. The Spring Drive 5 Days represents Grand Seiko\'s philosophical contrast to European complications: mastery of the surface rather than mastery of the mechanism.`),
  },
  {
    name: 'Spring Drive 5 Days Birch (White)',
    maker: 'Grand Seiko',
    reference: 'SBDB033',
    year: '2019',
    caseMaterial: 'Titanium',
    caseDiameter: '43.5mm',
    movement: 'Calibre 9R65 — Spring Drive, 5-day power reserve',
    complications: 'Spring Drive, 5-day power reserve',
    filterCategory: 'gs',
    order: 29,
    description: text(`White birch dial — the companion piece to the blue. The white variant reproduces the pale, almost luminescent quality of birch bark in winter. Both pieces were acquired together.`),
    notes: text(`White dial, titanium bracelet. Acquired as a pair with the blue birch variant. The two together demonstrate how Grand Seiko uses dial colour as seasonal language.`),
  },
  {
    name: 'Spring Drive Snowflake Shirogin',
    maker: 'Grand Seiko',
    reference: 'SBGA211',
    year: '2014',
    caseMaterial: 'Titanium',
    caseDiameter: '41mm',
    movement: 'Calibre 9R65 — Spring Drive',
    complications: 'Spring Drive',
    filterCategory: 'gs',
    order: 30,
    description: text(`The Snowflake — Grand Seiko's most recognised reference. The dial surface is textured to resemble the accumulated snow on Shinshu's mountainside, caught in low winter light. It does not tell the viewer what it represents; it simply presents itself. No date, no complication beyond the movement.`),
    notes: text(`Titanium, no date. The blue strap version of the SBGA211. The Snowflake is the watch TC most often recommends to someone beginning to understand Japanese watchmaking.`),
  },
  {
    name: 'Hi-Beat 36000 80hr (Ice Blue)',
    maker: 'Grand Seiko',
    reference: 'SLGH005',
    year: '2021',
    caseMaterial: 'Stainless steel',
    caseDiameter: '40mm',
    movement: 'Calibre 9SA5 — Hi-Beat 36000, 80-hour power reserve, dual impulse escapement',
    complications: '80-hour power reserve, dual impulse escapement',
    filterCategory: 'gs',
    order: 31,
    description: text(`Ice blue dial on steel bracelet — the SLGH005 introduced the new 9SA5 movement with dual impulse escapement, a mechanical innovation of genuine significance. The \'Seasons\' dial references the surface of Suwa Lake in winter.`),
    notes: text(`Steel bracelet, ice blue. The 9SA5 movement is Grand Seiko\'s most significant mechanical development since the Spring Drive. The dual impulse escapement delivers energy to the balance in both directions.`),
  },
  {
    name: 'Hi-Beat 36000 80hr (White)',
    maker: 'Grand Seiko',
    reference: 'SLGH003',
    year: '2021',
    caseMaterial: 'Stainless steel',
    caseDiameter: '40mm',
    movement: 'Calibre 9SA5 — Hi-Beat 36000, 80-hour power reserve, dual impulse escapement',
    complications: '80-hour power reserve, dual impulse escapement',
    filterCategory: 'gs',
    order: 32,
    description: text(`White dial variant of the SLGH series — the companion to the ice blue. The white dial texture references snowfall on the Shinshu plateau, the same geography that informs the Snowflake reference.`),
    notes: text(`Steel bracelet, white dial. Acquired alongside the ice blue as a pair — the two dial colours span the cold end of the Grand Seiko seasonal vocabulary.`),
  },
  {
    name: 'Hi-Beat GMT (Silver)',
    maker: 'Grand Seiko',
    reference: 'SBGJ201',
    year: '2017',
    caseMaterial: 'Stainless steel',
    caseDiameter: '40mm',
    movement: 'Calibre 9S86 — Hi-Beat 36000, GMT',
    complications: 'GMT',
    filterCategory: 'gs',
    order: 33,
    description: text(`Silver dial Hi-Beat GMT on bracelet — Grand Seiko's travel complication at its most classical. The GMT hand is independently set via the crown, allowing second-timezone tracking without disturbing the main time display.`),
    notes: text(`Steel bracelet, silver dial. The GMT references both serve travel utility and represent the full range of Hi-Beat finishing across different dial treatments.`),
  },
  {
    name: 'Hi-Beat GMT (Purple)',
    maker: 'Grand Seiko',
    reference: 'SBGJ231',
    year: '2020',
    caseMaterial: 'Stainless steel',
    caseDiameter: '40mm',
    movement: 'Calibre 9S86 — Hi-Beat 36000, GMT',
    complications: 'GMT',
    filterCategory: 'gs',
    order: 34,
    description: text(`Purple dial — the more recent of the two Hi-Beat GMT references. Grand Seiko's purple dials use the same mica-based coating process as the brand's most acclaimed seasonal references, producing a surface that shifts between blue-purple and grey depending on ambient light.`),
    notes: text(`Steel bracelet, purple dial. The purple GMT is the more assertive reference; the silver the more conservative. Together they cover the full range of Grand Seiko dial character in the Hi-Beat GMT line.`),
  },
  {
    name: 'Hi-Beat Automatic Green Gold',
    maker: 'Grand Seiko',
    reference: 'SBHM013',
    year: '2018',
    caseMaterial: 'Yellow gold',
    caseDiameter: '40mm',
    movement: 'Calibre 9SA1 — Hi-Beat 36000, automatic',
    complications: 'Hi-Beat 36000',
    filterCategory: 'gs',
    order: 35,
    description: text(`Yellow gold with green dial — one of the rarest configurations in the collection. Grand Seiko's green dials reference the lacquered surface of cedar trees in autumn. In yellow gold, the combination produces an effect of deliberate extravagance within a brand not typically associated with it.`),
    notes: text(`Yellow gold bracelet, green dial. The most unusual Grand Seiko in the collection — the gold case places it outside Grand Seiko's typical material vocabulary.`),
  },
  {
    name: 'Spring Drive Power Reserve',
    maker: 'Grand Seiko',
    reference: 'SBDB011',
    year: '2015',
    caseMaterial: 'Titanium',
    caseDiameter: '43.5mm',
    movement: 'Calibre 9R84 — Spring Drive, power reserve indicator',
    complications: 'Spring Drive, power reserve indication',
    filterCategory: 'gs',
    order: 36,
    description: text(`Titanium bracelet, Spring Drive with linear power reserve display. The power reserve is shown as a gradient arc at the top of the dial — a visual language borrowed from instrument gauges. When fully wound, the indicator sits at the right; as energy depletes it moves left.`),
    notes: text(`Titanium bracelet. The power reserve display adds a procedural dimension to wearing — the arc becoming a daily reminder of the movement\'s energy state.`),
  },
  {
    name: 'Hi-Beat 36000 GMT Sunray',
    maker: 'Grand Seiko',
    reference: 'SBGJ235',
    year: '2021',
    caseMaterial: 'Stainless steel',
    caseDiameter: '40mm',
    movement: 'Calibre 9S86 — Hi-Beat 36000, GMT',
    complications: 'GMT',
    filterCategory: 'gs',
    order: 37,
    description: text(`Blue sunray dial on leather strap — the dress configuration of the Hi-Beat GMT line. The sunray finishing produces a starburst of light from the dial centre, unlike the textural references of the studio production pieces.`),
    notes: text(`Steel on blue strap. The strap configuration makes this the most formal of the Grand Seiko GMT references in the collection.`),
  },

  // ── Rolex ─────────────────────────────────────────────────────────────────

  {
    name: "Submariner White Gold (Father's)",
    maker: 'Rolex',
    reference: '116619LB',
    year: '2010',
    caseMaterial: '18k white gold',
    caseDiameter: '40mm',
    movement: 'Calibre 3135 — automatic',
    complications: 'Date',
    filterCategory: 'rolex',
    order: 38,
    description: text(`TC's father's watch — the most personally significant piece in the collection. A white gold Submariner with blue ceramic bezel and blue dial. The first watch TC wore that made him understand what it meant to wear something with a history attached.`),
    notes: text(`Father's watch. White gold, blue dial. The story of this piece is the reason the collection exists. It will be written about at the appropriate moment — not before.`),
  },
  {
    name: 'Submariner Yellow Gold Serti',
    maker: 'Rolex',
    reference: '116618LB',
    year: '2012',
    caseMaterial: '18k yellow gold',
    caseDiameter: '40mm',
    movement: 'Calibre 3135 — automatic',
    complications: 'Date, diamond-set dial',
    filterCategory: 'rolex',
    order: 39,
    description: text(`Yellow gold Submariner with serti diamond dial — a configuration that tests the idea of what a dive watch can become when material constraints are removed. The diamonds are set into the dial rather than applied to it; the lumeé plots replaced with stones.`),
    notes: text(`Yellow gold, diamond serti dial. The serti configuration is the least subtle expression of the Submariner — acquired as a deliberate contrast to the collection\'s general preference for restraint.`),
  },
  {
    name: 'Submariner Onyx Yellow Gold',
    maker: 'Rolex',
    reference: '116618LN',
    year: '2018',
    caseMaterial: '18k yellow gold',
    caseDiameter: '40mm',
    movement: 'Calibre 3135 — automatic',
    complications: 'Date',
    filterCategory: 'rolex',
    order: 40,
    description: text(`Yellow gold with onyx black dial — acquired Hong Kong, March 2026, through Johnson167. The onyx dial produces a depth and opacity that the standard black dial cannot replicate. One of the cleanest Submariner configurations.`),
    notes: text(`Acquired Hong Kong March 2026, Johnson167. Yellow gold, onyx dial. The least common of the three gold Submariner references in the collection.`),
  },
  {
    name: 'Daytona Green',
    maker: 'Rolex',
    reference: '116508',
    year: '2020',
    caseMaterial: '18k yellow gold',
    caseDiameter: '40mm',
    movement: 'Calibre 4130 — automatic, chronograph',
    complications: 'Chronograph',
    filterCategory: 'rolex',
    order: 41,
    description: text(`Yellow gold Daytona with green dial — the most immediately recognisable configuration in the modern Daytona range. The green and gold combination references the racing heritage of the original Daytona, updated for a different kind of spectacle.`),
    notes: text(`Yellow gold, green dial. The green Daytona is the most requested photograph from the collection — a recognition that some watches need no context.`),
  },
  {
    name: 'Daytona Vintage',
    maker: 'Rolex',
    reference: '6265',
    year: '1972',
    caseMaterial: 'Yellow gold',
    caseDiameter: '37mm',
    movement: 'Calibre 727 — manually wound, Valjoux 72 base',
    complications: 'Chronograph',
    filterCategory: 'rolex',
    order: 42,
    description: text(`A vintage Daytona circa 1972 — yellow gold with exotic dial. The 6265 predates the in-house movement era; it runs a modified Valjoux 72 ébauche. The proportions are smaller, the crown protection absent, the register placement slightly different. A record of what the Daytona was before it became what it is.`),
    notes: text(`Yellow gold, circa 1972. The vintage Daytona provides chronological context for the modern references — the distance between them is as interesting as either piece alone.`),
  },
  {
    name: 'Day-Date Chinese Character Onyx',
    maker: 'Rolex',
    reference: '228238',
    year: '2019',
    caseMaterial: '18k yellow gold',
    caseDiameter: '40mm',
    movement: 'Calibre 3255 — automatic',
    complications: 'Day, date',
    filterCategory: 'rolex',
    order: 43,
    description: text(`Yellow gold Day-Date with Chinese character day disc and onyx dial — among the rarest Day-Date configurations available. The Chinese day disc replaces the standard Roman/Arabic characters with traditional Chinese ideograms, a factory option produced in very limited quantities.`),
    notes: text(`Yellow gold, onyx dial, Chinese character day disc. Acquired Hong Kong March 2026, Johnson167. The first of five Chinese character Day-Dates in the collection.`),
  },
  {
    name: 'Day-Date Chinese Character Set',
    maker: 'Rolex',
    reference: '228238',
    year: '2018–2022',
    caseMaterial: '18k yellow gold',
    caseDiameter: '40mm',
    movement: 'Calibre 3255 — automatic',
    complications: 'Day, date',
    filterCategory: 'rolex',
    order: 44,
    description: text(`A set of four additional Chinese character Day-Date references — accumulated through Johnson167 in Hong Kong over multiple visits. Rarely available configuration; finding multiples requires a patient, long-term relationship with a specialist dealer.`),
    notes: text(`Accumulated over several years. Acquiring five Chinese character Day-Dates represents one of the more unusual collecting positions in the Rolex world — a specialisation within a specialisation.`),
  },

  // ── Independents & Others ─────────────────────────────────────────────────

  {
    name: 'Reverso Gyrotourbillon 2',
    maker: 'Jaeger-LeCoultre',
    reference: 'Q6013420',
    year: '2008',
    caseMaterial: 'Rose gold',
    caseDiameter: '30 × 50mm',
    movement: 'Calibre 177 — manually wound, spherical tourbillon, perpetual calendar',
    complications: 'Spherical tourbillon, perpetual calendar',
    filterCategory: 'independent',
    order: 45,
    description: text(`Rose gold Reverso housing the Gyrotourbillon 2 — a tourbillon that rotates on two axes simultaneously, compensating for gravitational error in both the horizontal and vertical planes. Among the most complex movements ever fitted into a rectangular case.`),
    notes: text(`Rose gold. The Reverso format adds a mechanical dimension to the tourbillon — when reversed, the display side shows the case back and movement through a sapphire caseback.`),
  },
  {
    name: 'Reverso Skeleton',
    maker: 'Jaeger-LeCoultre',
    reference: 'Q3738490',
    year: '2015',
    caseMaterial: 'Rose gold',
    caseDiameter: '30 × 50mm',
    movement: 'Calibre 846 SQ — manually wound, skeletonised',
    complications: 'Skeletonisation',
    filterCategory: 'independent',
    order: 46,
    description: text(`Rose gold Reverso with skeletonised movement — both sides of the reversible case display the movement architecture. The skeletonisation is done to the point where the dial side shows only bridges and wheels; the back, the reverse.`),
    notes: text(`Rose gold. The second JLC in the collection. The two Reversos span different complication philosophies: one hyper-complex, one reduced to pure mechanism.`),
  },
  {
    name: 'De Bethune DB28 Galaxy',
    maker: 'De Bethune',
    reference: 'DB28GS',
    year: '2017',
    caseMaterial: 'Rose gold',
    caseDiameter: '42.6mm',
    movement: 'Calibre DB2115 — manually wound, tourbillon, moon phase',
    complications: 'Spherical moon phase, tourbillon',
    filterCategory: 'independent',
    order: 47,
    description: text(`Rose gold with blue aventurine dial — a piece of the night sky mounted in a watch case. De Bethune's aventurine glass galaxy dial contains actual mineral aventurine, its copper-schist particles reflecting light unpredictably. The spherical moon phase at 12 o'clock rotates to display the actual illuminated portion of the moon.`),
    notes: text(`Rose gold, aventurine dial. De Bethune is among the most technically ambitious independent manufactures — their escapement geometry is their own. The Galaxy is the collection's most visually unusual piece.`),
  },
  {
    name: 'MING 17.09 Aventurine',
    maker: 'MING',
    reference: '17.09',
    year: '2019',
    caseMaterial: 'Stainless steel',
    caseDiameter: '38mm',
    movement: 'Calibre SH21 — automatic, 72-hour power reserve',
    complications: '',
    filterCategory: 'independent',
    order: 48,
    description: text(`Blue aventurine dial on steel bracelet — one of a very small production run from the Kuala Lumpur-based independent MING. The collaboration between designer Ming Thein and movement supplier Schwarz Etienne produces watches that compete technically and aesthetically with European pieces at a fraction of the production volume.`),
    notes: text(`Steel bracelet, aventurine dial. MING represents a new geography of independent watchmaking — not Geneva, not Glashütte, but Southeast Asia. Its inclusion makes an argument about where good watchmaking can come from.`),
  },
  {
    name: 'MING 18.01 Black Lacquer',
    maker: 'MING',
    reference: '18.01',
    year: '2018',
    caseMaterial: 'Stainless steel',
    caseDiameter: '38mm',
    movement: 'Calibre SH21 — automatic, 72-hour power reserve',
    complications: '',
    filterCategory: 'independent',
    order: 49,
    description: text(`Black lacquer dial on grey rubber strap — the more minimal of the two MING references. The lacquer dial is applied in multiple layers, each cured separately. The result is a depth of surface that photographs cannot fully reproduce.`),
    notes: text(`Steel on grey rubber. The black lacquer MING is the more wearable reference — the rubber strap and restrained dial make it the piece most often on the wrist in casual contexts.`),
  },
]

async function importWatches() {
  console.log(`Importing ${watches.length} watches...`)

  const transaction = client.transaction()
  for (const watch of watches) {
    const doc = {
      _type: 'watch',
      _id: `watch-${slug(watch.name)}`,
      name: watch.name,
      slug: { _type: 'slug', current: slug(watch.name) },
      maker: watch.maker,
      reference: watch.reference || '',
      year: watch.year || '',
      caseMaterial: watch.caseMaterial || '',
      caseDiameter: watch.caseDiameter || '',
      movement: watch.movement || '',
      complications: watch.complications || '',
      filterCategory: watch.filterCategory,
      order: watch.order,
      description: watch.description,
      notes: watch.notes,
    }
    transaction.createOrReplace(doc)
  }

  try {
    const result = await transaction.commit()
    console.log(`✅ Imported ${watches.length} watches successfully`)
    console.log(`Transaction ID: ${result.transactionId}`)
  } catch (err) {
    console.error('❌ Import failed:', err.message)
    process.exit(1)
  }
}

importWatches()
